{% set name = "uvicorn" %}
{% set version = "0.3.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82f5ea4e838fb3014b3009d5f27908359837cb41119536487d97867a84b183b4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [py2k]
  entry_points:
    - uvicorn = uvicorn.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - h11
    - websockets >=6.0
    - uvloop  # [not win]
    - httptools  # [not win]

test:
  imports:
    - uvicorn
  commands:
    - uvicorn --help

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'The lightning-fast ASGI server. 🦄'
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  recipe-maintainers:
    - carlodri
