{% set name = "uvicorn" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec3533a8d0aa9ebf941a4edd4735d91e10925e6825dd6e86d6163ac4e5b42835

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py2k]
  entry_points:
    - uvicorn = uvicorn.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click =7
    - h11 =0.8
    - websockets =7
    - uvloop =0.12  # [not win]
    - httptools =0.0.13  # [not win]
    - wsproto =0.13

test:
  imports:
    - uvicorn
  commands:
    - uvicorn --help

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'The lightning-fast ASGI server. 🦄'
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  recipe-maintainers:
    - carlodri
