{% set version = "0.11.3" %}

package:
  name: uvicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uvicorn/uvicorn-{{ version }}.tar.gz
  sha256: 6fdaf8e53bf1b2ddf0fe9ed06079b5348d7d1d87b3365fe2549e6de0d49e631c

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py2k]
  entry_points:
    - uvicorn = uvicorn.main:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click =7
    - h11 >=0.8,<0.10
    - websockets =8
    - httptools =0.1  # [not win]
    - uvloop >=0.14.0  # [not win]
    - wsproto =0.13
    - gunicorn  # [not win]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - uvicorn
  commands:
    - uvicorn --help

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'The lightning-fast ASGI server. 🦄'
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  recipe-maintainers:
    - carlodri
    - ocefpaf
