{% set version = "0.18.1" %}

package:
  name: uvicorn-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uvicorn/uvicorn-{{ version }}.tar.gz
  sha256: 35703e6518105cfe53f16a5a9435db3e2e227d0784f1fd8fbc1214b1fdc108df

build:
  number: 0

outputs:
  - name: uvicorn

    build:
      entry_points:
        - uvicorn = uvicorn.main:main
    script: uvicorn_build.bat  # [win]
    script: uvicorn_build.sh  # [not win]

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
      run:
        - python
        - asgiref >=3.4.0
        - click >=7.*
        - h11 >=0.8
        - typing-extensions  # [py<38]

    test:
      requires:
        - pip
      imports:
        - uvicorn
      commands:
        - pip check
        - uvicorn --help

  - name: uvicorn-standard

    requirements:
      host:
        - python
        - pip
        - {{ pin_subpackage('uvicorn', exact=True) }}
      run:
        - {{ pin_subpackage('uvicorn', exact=True) }}
        - websockets >=10.0
        - httptools >=0.2.0,<0.4.0
        - uvloop >=0.14.0,!=0.15.0,!=0.15.1  # [python_impl == "cpython" and not win]
        - colorama >=0.4  # [win]
        - watchgod >=0.6
        - python-dotenv >=0.13
        - PyYAML >=5.1

    test:
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server.
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  feedstock-name: uvicorn
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
