{% set version = "0.33.0" %}

# handle unset values during re-rendering
{% set PYTHON = PYTHON | default("$PYTHON") %}
{% set noarch_platform = noarch_platform | default("unix") %}

package:
  name: uvicorn
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/uvicorn/uvicorn-{{ version }}.tar.gz
  sha256: 3577119f82b7091cf4d3d4177bfda0bae4723ed92ab1439e8d779de880c9cc59

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed --disable-pip-version-check
  entry_points:
    - uvicorn = uvicorn.main:main

requirements:
  host:
    - __{{ noarch_platform }}
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - __{{ noarch_platform }}
    - click >=7.0
    - h11 >=0.8
    - python >={{ python_min }}
    - typing_extensions >=4.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - uvicorn
  commands:
    - pip check
    - uvicorn --help

outputs:
  - name: uvicorn

  - name: uvicorn-standard
    build:
      noarch: generic
    requirements:
      run:
        - __{{ noarch_platform }}
        - {{ pin_subpackage("uvicorn", exact=True) }}
        {% if noarch_platform == "win" %}
        - colorama >=0.4
        {% elif noarch_platform == "unix" %}
        - uvloop >=0.14.0,!=0.15.0,!=0.15.1
        {% endif %}
        - websockets >=10.4
        - httptools >=0.5.0
        - watchfiles >=0.13
        - python-dotenv >=0.13
        - pyyaml >=5.1
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - uvicorn.supervisors.watchfilesreload

about:
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server.
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  doc_url: https://www.uvicorn.org/
  dev_url: https://github.com/encode/uvicorn

extra:
  feedstock-name: uvicorn
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
