# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.41.0"
  python_check_max: "3.14"

recipe:
  name: uvicorn
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/u/uvicorn/uvicorn-${{ version }}.tar.gz
  sha256: 09d11cf7008da33113824ee5a1c6422d89fbc2ff476540d69a34c87fab8b571a

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: uvicorn
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed --disable-pip-version-check
      python:
        entry_points:
          - uvicorn = uvicorn.main:main
    requirements:
      host:
        - hatchling
        - pip
        - python ${{ python_min }}.*
      run:
        - __${{ noarch_platform }}
        - click >=7.0
        - h11 >=0.8
        - python >=${{ python_min }}
        - typing_extensions >=4.0
    tests:
      - python:
          imports: uvicorn
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script:
          - uvicorn --help

  - package:
      name: uvicorn-standard
    build:
      noarch: generic
    requirements:
      run:
        - __${{ noarch_platform }}
        - ${{ pin_subpackage("uvicorn", exact=True) }}
        - websockets >=10.4
        - httptools >=0.6.3
        - watchfiles >=0.20
        - python-dotenv >=0.13
        - pyyaml >=5.1
        - if: noarch_platform == "win"
          then:
            - colorama >=0.4
          else:
            - uvloop >=0.15.1
    tests:
      - python:
          imports: uvicorn.supervisors.watchfilesreload
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server.
  description: |
    Uvicorn is a lightning-fast ASGI server implementation,
    using [uvloop](https://github.com/MagicStack/uvloop) and
    [httptools](https://github.com/MagicStack/httptools).
  homepage: https://pypi.org/project/uvicorn
  repository: https://github.com/encode/uvicorn
  documentation: https://uvicorn.dev

extra:
  feedstock-name: uvicorn
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
