# Don't automerge, uvicorn-standard dependencies regularly change and need to edited manually.
# bot: {automerge: true}
build_platform:
  osx_arm64: osx_64
  linux_ppc64le: linux_ppc64le
  linux_aarch64: linux_aarch64
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
conda_forge_output_validation: true
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
